import React,{useEffect,useRef,useState}from'react';import{createRoot}from'react-dom/client';import'./style.css';
const Arrow=({className=''})=><div className={'arrow '+className}><span/><span/><span/></div>;
function App(){const[run,setRun]=useState(false),[scene,setScene]=useState(0),cv=useRef(null);useEffect(()=>{const c=cv.current,x=c.getContext('2d');let raf,t=0,stars=[];const reset=()=>{c.width=innerWidth;c.height=innerHeight;stars=Array.from({length:520},()=>({x:(Math.random()-.5)*c.width*1.8,y:(Math.random()-.5)*c.height*1.8,z:Math.random()*1+.02,s:Math.random()*1.8+.3}))};reset();addEventListener('resize',reset);function draw(){t+=.016;x.clearRect(0,0,c.width,c.height);x.save();x.translate(c.width/2,c.height/2);for(const p of stars){let speed=run?(10+scene*8):.15;p.z-=speed*.002;if(p.z<=.01){p.z=1;p.x=(Math.random()-.5)*c.width*1.8;p.y=(Math.random()-.5)*c.height*1.8}const sx=p.x/p.z,sy=p.y/p.z,px=p.x/(p.z+speed*.006),py=p.y/(p.z+speed*.006);x.globalAlpha=Math.min(1,(1-p.z)*.9+.08);x.strokeStyle='#fff';x.lineWidth=p.s;x.beginPath();x.moveTo(px,py);x.lineTo(sx,sy);x.stroke()}x.restore();raf=requestAnimationFrame(draw)}draw();return()=>{cancelAnimationFrame(raf);removeEventListener('resize',reset)}},[run,scene]);
function start(){if(run)return;setRun(true);setScene(1);[850,2300,4100,6200,8400,10800].forEach((ms,i)=>setTimeout(()=>setScene(i+2),ms))}
const words=['MESSAGES','FILES','PROJECTS','PEOPLE','EVENTS','IDEAS','TASKS','MUSIC','NOTES','AI','CALENDAR','MEMORIES'];
return <main className={'scene s'+scene+(run?' running':'')}><canvas ref={cv}/><div className="grain"/><div className="vignette"/>{!run&&<><div className="mega">ARROW</div><div className="ghosts">{Array.from({length:34},(_,i)=><Arrow key={i} className={'g g'+i}/>)}</div><button className="core" onClick={start}><Arrow/><em>CLICK TO INITIATE</em></button></>}
{scene===1&&<><div className="mega shatter">ARROW</div><div className="impact"/><div className="beam"/><div className="rings"/><div className="ship"><Arrow/></div></>}
{scene===2&&<><div className="speedlines"/><div className="tagline">GIVE YOUR LIFE <strong>DIRECTION.</strong></div><div className="fly"><Arrow/></div></>}
{scene===3&&<div className="chaos">{words.map((w,i)=><div key={w} className={'word w'+i}>{w}</div>)}<div className="fly center"><Arrow/></div></div>}
{scene===4&&<><div className="pulse"/><div className="organize">{words.slice(0,8).map((w,i)=><div className={'node n'+i} key={w}><i/>{w}</div>)}</div><div className="caption">CHAOS BECOMES <b>DIRECTION.</b></div></>}
{scene===5&&<div className="modules"><div className="orb"/>{['ATLAS','RAVIN','RELAY','ORBIT'].map((m,i)=><div className={'module m'+i} key={m}><i/>{m}<small>{['YOUR WORLD','INTELLIGENCE','CONNECTION','THE CENTER'][i]}</small></div>)}<div className="fly orbit"><Arrow/></div></div>}
{scene===6&&<div className="final"><div className="sun"/><Arrow className="finalArrow"/><h1>PROJECT ARROW</h1><h2>YOUR LIFE. CONNECTED.</h2><p>GIVE IT DIRECTION.</p></div>}
{scene>=7&&<section className="landing"><Arrow/><h1>ARROW</h1><h2>Your life has a lot of moving parts.<br/>Bring them into one direction.</h2><div><button onClick={()=>location.reload()}>REPLAY EXPERIENCE</button><button>EXPLORE ARROW →</button></div></section>}<div className="brand">RESONANT ASSIST <b>/</b> PROJECT ARROW</div></main>}createRoot(document.getElementById('root')).render(<App/>);